get:
  summary: Get a product model
  operationId: "get_product_models__code_"
  tags:
    - Product models
  x-versions:
    - 2.0
  description: This endpoint allows you to get the information about a given product model.
  parameters:
    - $ref: '#/parameters/code'
  responses:
    200:
      description: OK
      x-details: Returns the content of the product model in JSON standard format.
      schema:
        $ref: '#/definitions/ProductModel'
    401:
      $ref: "#/responses/401Error"
    404:
      $ref: "#/responses/404Error"
    406:
      $ref: "#/responses/406Error"
patch:
  summary: Update/create a product model
  operationId: "patch_product_models__code_"
  tags:
    - Product models
  x-versions:
    - 2.0
  description: This endpoint allows you to update a given product model. Know more about <a href="/documentation/update.html#update-behavior">Update behavior</a>. Note that if no product model exists for the given code, it creates it. If you are using a v2.0 Enterprise Edition PIM, permissions based on your user groups are applied to the product model you try to update. It may result in the creation of a draft if you only have edit rights through the product model's categories.
  parameters:
    - $ref: '#/parameters/code'
    - name: body
      in: body
      required: true
      schema:
        $ref: "#/definitions/ProductModel"
  responses:
    201:
      $ref: "#/responses/Created"
    204:
      $ref: "#/responses/NoContent"
    401:
      $ref: "#/responses/401Error"
    415:
      $ref: "#/responses/415Error"
    422:
      $ref: "#/responses/422Error"
